/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DrizzleDrizzleMigrations {
  created_at: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface Skills {
  category: string;
  created_at: Generated<Timestamp>;
  description: string;
  display_order: number;
  id: Generated<number>;
  level: number;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "drizzle.__drizzle_migrations": DrizzleDrizzleMigrations;
  skills: Skills;
}
